### ISSUE TITLE
npm run migrate: "Cannot read property 'oracle' of undefined"

### ISSUE THREAD

**Issue by 7-of-9** [linkpoolio/example-chainlinks#4]
4_api_aggregator_consumer.js
============================

TypeError: Cannot read property 'oracle' of undefined
    at module.exports (/Users/dom/src/example-chainlinks/migrations/4_api_aggregator_consumer.js:8:12)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/migration.js:56:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.1 (core: 5.1.1)
Node v10.16.2

**Comment by jleeh** [comment]
Should be fixed on master, apologies for the delay.
